version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # TODO: enable corepack on AWS Beanstalk in order to avoid global install
      # - corepack enable
      # - corepack prepare pnpm@latest --activate
      - cd chtter-backend
      #- pnpm install --frozen-lockfile
      - npm install -g pnpm
  
  pre_build:
    commands:
      - pnpm install

  build:
    commands:
      - pnpm run build

artifacts:
  base-directory: chtter-backend
  files:
    - dist/**/*       
    - package.json    
    - pnpm-lock.yaml    
    - Procfile 
