version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - pnpm install

  build:
    commands:
      - pnpm run build

artifacts:
  base-directory: chtter-backend
  files:
    - dist/**/*
    - package.json
    - pnpm-lock.yaml
    - Procfile